/**
 * @fileoverview gRPC-Web generated client stub for finternet
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: proto/service.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as proto_service_pb from '../proto/service_pb'; // proto import: "proto/service.proto"


export class DriverClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorLoadDriver = new grpcWeb.MethodDescriptor(
    '/finternet.Driver/LoadDriver',
    grpcWeb.MethodType.UNARY,
    proto_service_pb.LoadDriverRequest,
    proto_service_pb.LoadDriverResponse,
    (request: proto_service_pb.LoadDriverRequest) => {
      return request.serializeBinary();
    },
    proto_service_pb.LoadDriverResponse.deserializeBinary
  );

  loadDriver(
    request: proto_service_pb.LoadDriverRequest,
    metadata?: grpcWeb.Metadata | null): Promise<proto_service_pb.LoadDriverResponse>;

  loadDriver(
    request: proto_service_pb.LoadDriverRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_service_pb.LoadDriverResponse) => void): grpcWeb.ClientReadableStream<proto_service_pb.LoadDriverResponse>;

  loadDriver(
    request: proto_service_pb.LoadDriverRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_service_pb.LoadDriverResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/finternet.Driver/LoadDriver',
        request,
        metadata || {},
        this.methodDescriptorLoadDriver,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/finternet.Driver/LoadDriver',
    request,
    metadata || {},
    this.methodDescriptorLoadDriver);
  }

  methodDescriptorUnloadDriver = new grpcWeb.MethodDescriptor(
    '/finternet.Driver/UnloadDriver',
    grpcWeb.MethodType.UNARY,
    proto_service_pb.UnloadDriverRequest,
    proto_service_pb.UnloadDriverResponse,
    (request: proto_service_pb.UnloadDriverRequest) => {
      return request.serializeBinary();
    },
    proto_service_pb.UnloadDriverResponse.deserializeBinary
  );

  unloadDriver(
    request: proto_service_pb.UnloadDriverRequest,
    metadata?: grpcWeb.Metadata | null): Promise<proto_service_pb.UnloadDriverResponse>;

  unloadDriver(
    request: proto_service_pb.UnloadDriverRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_service_pb.UnloadDriverResponse) => void): grpcWeb.ClientReadableStream<proto_service_pb.UnloadDriverResponse>;

  unloadDriver(
    request: proto_service_pb.UnloadDriverRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_service_pb.UnloadDriverResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/finternet.Driver/UnloadDriver',
        request,
        metadata || {},
        this.methodDescriptorUnloadDriver,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/finternet.Driver/UnloadDriver',
    request,
    metadata || {},
    this.methodDescriptorUnloadDriver);
  }

  methodDescriptorListResolver = new grpcWeb.MethodDescriptor(
    '/finternet.Driver/ListResolver',
    grpcWeb.MethodType.UNARY,
    proto_service_pb.ListResolverRequest,
    proto_service_pb.ListResolverResponse,
    (request: proto_service_pb.ListResolverRequest) => {
      return request.serializeBinary();
    },
    proto_service_pb.ListResolverResponse.deserializeBinary
  );

  listResolver(
    request: proto_service_pb.ListResolverRequest,
    metadata?: grpcWeb.Metadata | null): Promise<proto_service_pb.ListResolverResponse>;

  listResolver(
    request: proto_service_pb.ListResolverRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_service_pb.ListResolverResponse) => void): grpcWeb.ClientReadableStream<proto_service_pb.ListResolverResponse>;

  listResolver(
    request: proto_service_pb.ListResolverRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_service_pb.ListResolverResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/finternet.Driver/ListResolver',
        request,
        metadata || {},
        this.methodDescriptorListResolver,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/finternet.Driver/ListResolver',
    request,
    metadata || {},
    this.methodDescriptorListResolver);
  }

}

export class BindClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorBind = new grpcWeb.MethodDescriptor(
    '/finternet.Bind/Bind',
    grpcWeb.MethodType.UNARY,
    proto_service_pb.BindRequest,
    proto_service_pb.BindResponse,
    (request: proto_service_pb.BindRequest) => {
      return request.serializeBinary();
    },
    proto_service_pb.BindResponse.deserializeBinary
  );

  bind(
    request: proto_service_pb.BindRequest,
    metadata?: grpcWeb.Metadata | null): Promise<proto_service_pb.BindResponse>;

  bind(
    request: proto_service_pb.BindRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_service_pb.BindResponse) => void): grpcWeb.ClientReadableStream<proto_service_pb.BindResponse>;

  bind(
    request: proto_service_pb.BindRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_service_pb.BindResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/finternet.Bind/Bind',
        request,
        metadata || {},
        this.methodDescriptorBind,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/finternet.Bind/Bind',
    request,
    metadata || {},
    this.methodDescriptorBind);
  }

  methodDescriptorUnbind = new grpcWeb.MethodDescriptor(
    '/finternet.Bind/Unbind',
    grpcWeb.MethodType.UNARY,
    proto_service_pb.UnbindRequest,
    proto_service_pb.UnbindResponse,
    (request: proto_service_pb.UnbindRequest) => {
      return request.serializeBinary();
    },
    proto_service_pb.UnbindResponse.deserializeBinary
  );

  unbind(
    request: proto_service_pb.UnbindRequest,
    metadata?: grpcWeb.Metadata | null): Promise<proto_service_pb.UnbindResponse>;

  unbind(
    request: proto_service_pb.UnbindRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_service_pb.UnbindResponse) => void): grpcWeb.ClientReadableStream<proto_service_pb.UnbindResponse>;

  unbind(
    request: proto_service_pb.UnbindRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_service_pb.UnbindResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/finternet.Bind/Unbind',
        request,
        metadata || {},
        this.methodDescriptorUnbind,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/finternet.Bind/Unbind',
    request,
    metadata || {},
    this.methodDescriptorUnbind);
  }

}

export class ExecutionClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorExecute = new grpcWeb.MethodDescriptor(
    '/finternet.Execution/Execute',
    grpcWeb.MethodType.UNARY,
    proto_service_pb.ExecutionRequest,
    proto_service_pb.ExecutionResponse,
    (request: proto_service_pb.ExecutionRequest) => {
      return request.serializeBinary();
    },
    proto_service_pb.ExecutionResponse.deserializeBinary
  );

  execute(
    request: proto_service_pb.ExecutionRequest,
    metadata?: grpcWeb.Metadata | null): Promise<proto_service_pb.ExecutionResponse>;

  execute(
    request: proto_service_pb.ExecutionRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_service_pb.ExecutionResponse) => void): grpcWeb.ClientReadableStream<proto_service_pb.ExecutionResponse>;

  execute(
    request: proto_service_pb.ExecutionRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_service_pb.ExecutionResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/finternet.Execution/Execute',
        request,
        metadata || {},
        this.methodDescriptorExecute,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/finternet.Execution/Execute',
    request,
    metadata || {},
    this.methodDescriptorExecute);
  }

  methodDescriptorSubmit = new grpcWeb.MethodDescriptor(
    '/finternet.Execution/Submit',
    grpcWeb.MethodType.UNARY,
    proto_service_pb.SubmitProgramRequest,
    proto_service_pb.SubmitProgramResponse,
    (request: proto_service_pb.SubmitProgramRequest) => {
      return request.serializeBinary();
    },
    proto_service_pb.SubmitProgramResponse.deserializeBinary
  );

  submit(
    request: proto_service_pb.SubmitProgramRequest,
    metadata?: grpcWeb.Metadata | null): Promise<proto_service_pb.SubmitProgramResponse>;

  submit(
    request: proto_service_pb.SubmitProgramRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_service_pb.SubmitProgramResponse) => void): grpcWeb.ClientReadableStream<proto_service_pb.SubmitProgramResponse>;

  submit(
    request: proto_service_pb.SubmitProgramRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_service_pb.SubmitProgramResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/finternet.Execution/Submit',
        request,
        metadata || {},
        this.methodDescriptorSubmit,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/finternet.Execution/Submit',
    request,
    metadata || {},
    this.methodDescriptorSubmit);
  }

  methodDescriptorList = new grpcWeb.MethodDescriptor(
    '/finternet.Execution/List',
    grpcWeb.MethodType.UNARY,
    proto_service_pb.ListProgramRequest,
    proto_service_pb.ListProgramResponse,
    (request: proto_service_pb.ListProgramRequest) => {
      return request.serializeBinary();
    },
    proto_service_pb.ListProgramResponse.deserializeBinary
  );

  list(
    request: proto_service_pb.ListProgramRequest,
    metadata?: grpcWeb.Metadata | null): Promise<proto_service_pb.ListProgramResponse>;

  list(
    request: proto_service_pb.ListProgramRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_service_pb.ListProgramResponse) => void): grpcWeb.ClientReadableStream<proto_service_pb.ListProgramResponse>;

  list(
    request: proto_service_pb.ListProgramRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_service_pb.ListProgramResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/finternet.Execution/List',
        request,
        metadata || {},
        this.methodDescriptorList,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/finternet.Execution/List',
    request,
    metadata || {},
    this.methodDescriptorList);
  }

}

export class DriverDetailsClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorSendDetails = new grpcWeb.MethodDescriptor(
    '/finternet.DriverDetails/SendDetails',
    grpcWeb.MethodType.UNARY,
    proto_service_pb.DriverDetailsRequest,
    proto_service_pb.DriverDetailsResponse,
    (request: proto_service_pb.DriverDetailsRequest) => {
      return request.serializeBinary();
    },
    proto_service_pb.DriverDetailsResponse.deserializeBinary
  );

  sendDetails(
    request: proto_service_pb.DriverDetailsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<proto_service_pb.DriverDetailsResponse>;

  sendDetails(
    request: proto_service_pb.DriverDetailsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_service_pb.DriverDetailsResponse) => void): grpcWeb.ClientReadableStream<proto_service_pb.DriverDetailsResponse>;

  sendDetails(
    request: proto_service_pb.DriverDetailsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_service_pb.DriverDetailsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/finternet.DriverDetails/SendDetails',
        request,
        metadata || {},
        this.methodDescriptorSendDetails,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/finternet.DriverDetails/SendDetails',
    request,
    metadata || {},
    this.methodDescriptorSendDetails);
  }

}

