
build-transfer: 
	RUSTFLAGS="-C target-feature=+multivalue" cargo build --target wasm32-unknown-unknown --release --features transfer
build-view:
	RUSTFLAGS="-C target-feature=+multivalue" cargo build --target wasm32-unknown-unknown --release --features view
